package com.cdancy.etcdjava;

import co.cask.http.NettyHttpService;
import com.cdancy.etcdjava.controllers.Miscellaneous;
import com.google.common.collect.ImmutableList;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cdancy' at '10/6/16 4:49 PM' with Gradle 2.14.1
 *
 * @author cdancy, @date 10/6/16 4:49 PM
 */
public class EtcdJavaServerTest {
    
    private EtcdJavaServerTest() {
        
    }
    
    public static void main(String [] args) {
                // Setup HTTP service and add Handlers
        NettyHttpService service = NettyHttpService.builder("etcd-java")
                .setExceptionHandler(null)
                                   .setPort(7777)
                                   .addHttpHandlers(ImmutableList.of(new Miscellaneous()))
                                   .build();


        try {
            Thread.sleep(100000);
        } catch (InterruptedException ex) {
            Logger.getLogger(EtcdJavaServerTest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public static class Builder {
        
    }
}


