package com.cdancy.etcdjava;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cdancy' at '10/6/16 4:49 PM' with Gradle 2.14.1
 *
 * @author cdancy, @date 10/6/16 4:49 PM
 */
public class EtcdJava {
        
    private static final Logger logger = LoggerFactory.getLogger(EtcdJava.class);

    private final ClientServer clientServer;
    private final PeerServer peerServer;
    
    public EtcdJava() {
        clientServer = new ClientServer();
        peerServer = new PeerServer();
    }
    
    public synchronized void start() {
        logger.info("Starting etcd-java ...");
        peerServer.start();
        clientServer.start();
        logger.info("Started etcd-java ...");
    }
    
    public synchronized void stop() {
        
        logger.info("Stopping etcd-java ...");
        try {
            clientServer.stop();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        try {
            peerServer.stop();
        } catch (Exception e) {
            e.printStackTrace();
        }
        logger.info("Stopping etcd-java ...");
    }
    
    public static void main(String [] args) throws Exception {
        
        EtcdJava server = new EtcdJava();
        server.start();
        
        Thread.sleep(20000);
        
        server.stop();
    }
}

